### ISSUE TITLE
Add option for plugins

### ISSUE THREAD

**Issue by zharikovpro** [blocknotes/activeadmin_selectize#1]
Currently, there's no easy way to setup plugins via data attributes. Only can modify included init script. Would be great to parse JSON from data-opt-plugins. Specifically I needed this for drag_drop, very useful for ordered collections.

**Comment by blocknotes** [comment]
@zharikovpro: ok - I have just added a new method to override Selectize options directly, it should improve the usability.
Example: `'data-options': '{"highlight":true,"plugins":[]}'`

**Comment by blocknotes** [comment]
I consider it as solved with the last changes
